// List of motivational quotes
const quotes = [
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "Your limitation—it's only your imagination.",
    "Push yourself, because no one else is going to do it for you.",
    "Sometimes later becomes never. Do it now.",
    "Great things never come from comfort zones.",
    "Dream it. Wish it. Do it.",
    "Success doesn't just find you. You have to go out and get it.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Dream bigger. Do bigger.",
    "Don't stop when you're tired. Stop when you're done.",
"The only way to do great work is to love what you do",  
"Success is not the key to happiness, happiness is the key to success",  
"Don’t watch the clock, do what it does—keep going",  
"Believe you can and you're halfway there",  
"Success is the sum of small efforts repeated day in and day out",  
"Your limitation is only your imagination",  
"Push yourself, because no one else is going to do it for you",  
"Dream it, wish it, do it",  
"Great things never come from comfort zones",  
"Success doesn’t just find you, you have to go out and get it",  
"The harder you work for something, the greater you’ll feel when you achieve it",  
"Dream bigger, do bigger",  
"Don’t stop when you’re tired, stop when you’re done",  
"Wake up with determination, go to bed with satisfaction",  
"Do something today that your future self will thank you for",  
"Little things make big days",  
"It’s going to be hard, but hard does not mean impossible",  
"Don’t wait for opportunity, create it",  
"Sometimes we’re tested not to show our weaknesses, but to discover our strengths",  
"The key to success is to focus on goals, not obstacles",  
"You don’t have to be great to start, but you have to start to be great",  
"The best time to plant a tree was 20 years ago, the second-best time is now",  
"You are never too old to set another goal or to dream a new dream",  
"If you’re not willing to risk the usual, you will have to settle for the ordinary",  
"You don’t have to see the whole staircase, just take the first step",  
"If you can’t stop thinking about it, don’t stop working for it",  
"Hard times don’t create heroes, it is during hard times that the hero within us is revealed",  
"Do what you can with all you have, wherever you are",  
"Success is not final, failure is not fatal, it is the courage to continue that counts",  
"Life is 10% what happens to us and 90% how we react to it",  
"Happiness is not something ready-made, it comes from your own actions",  
"Start where you are, use what you have, do what you can",  
"A person who never made a mistake never tried anything new",  
"The secret to getting ahead is getting started",  
"Your life does not get better by chance, it gets better by change",  
"Don’t let yesterday take up too much of today",  
"You learn more from failure than from success, don’t let it stop you",  
"It’s not whether you get knocked down, it’s whether you get up",  
"The harder the battle, the sweeter the victory",  
"Go the extra mile, it’s never crowded",  
"Keep your eyes on the stars, and your feet on the ground",  
"Success is walking from failure to failure with no loss of enthusiasm",  
"Don’t be afraid to give up the good to go for the great",  
"You miss 100% of the shots you don’t take",  
"Fall seven times, stand up eight",  
"Success usually comes to those who are too busy to be looking for it",  
"The only limit to our realization of tomorrow is our doubts of today",  
"What you get by achieving your goals is not as important as what you become by achieving them",  
"Don’t count the days, make the days count",  
"Work hard in silence, let your success be your noise",  
"Doubt kills more dreams than failure ever will",  
"Don’t be pushed around by the fears in your mind, be led by the dreams in your heart",  
"Don’t limit your challenges, challenge your limits",  
"The future belongs to those who believe in the beauty of their dreams",  
"If you want something you’ve never had, you must be willing to do something you’ve never done",  
"Your only limit is you",  
"Work hard, stay consistent, and be patient",  
"The difference between ordinary and extraordinary is that little extra",  
"When everything seems to be going against you, remember that the airplane takes off against the wind, not with it",  
"You are braver than you believe, stronger than you seem, and smarter than you think",  
"Start where you are, use what you have, do what you can",  
"Don’t give up because you had a bad day, forgive yourself and do better tomorrow",  
"A winner is a dreamer who never gives up",  
"Do what is right, not what is easy",  
"You can’t go back and change the beginning, but you can start where you are and change the ending",  
"Failure is the opportunity to begin again more intelligently",  
"Success is not how high you have climbed, but how you make a positive difference to the world",  
"Perseverance is not a long race; it is many short races one after another",  
"Do what you have to do until you can do what you want to do",  
"Action is the foundational key to all success",  
"Success is what happens after you have survived all of your mistakes",  
"If you want to fly, you have to give up the things that weigh you down",  
"Don’t wish for it, work for it",  
"Success comes from having dreams that are bigger than your fears",  
"Your potential is endless",  
"Don’t quit, suffer now and live the rest of your life as a champion",  
"Stop doubting yourself, work hard, and make it happen",  
"The best view comes after the hardest climb",  
"Don’t stop until you’re proud",  
"You only fail when you stop trying",  
"Every day is a new beginning, take a deep breath and start again",  
"Believe in yourself and all that you are",  
"Do it now, sometimes later becomes never",  
"Success is what happens after you’ve done all the hard work",  
"Take the risk or lose the chance",  
"Everything you’ve ever wanted is on the other side of fear",  
"The only way to achieve the impossible is to believe it is possible",  
"Set a goal that makes you want to jump out of bed in the morning",  
"Don’t call it a dream, call it a plan",  
"The distance between dreams and reality is called action",  
"Hardships often prepare ordinary people for an extraordinary destiny",  
"You are capable of amazing things",  
"One day or day one, you decide",  
"Success is getting what you want, happiness is wanting what you get",  
"You are what you repeatedly do, excellence is not an act, but a habit",  
"Don’t dream about success, get up and work for it",  
"Turn your obstacles into opportunities",  
"Difficult roads often lead to beautiful destinations",  
"Strive for progress, not perfection",  
"Small steps in the right direction can turn out to be the biggest step of your life",
    
];

// List of background classes
const backgrounds = ['bg1', 'bg2', 'bg3', 'bg4', 'bg5'];

// Function to get a random element from an array
function getRandomElement(array) {
    return array[Math.floor(Math.random() * array.length)];
}

// Set a random quote
document.getElementById("quote").textContent = getRandomElement(quotes);

// Change background color randomly
const body = document.body;
body.classList.add(getRandomElement(backgrounds));
